### ISSUE TITLE
scroll problem in WeChat Android

### ISSUE THREAD

**Issue by yiranzi** [amio/re-carousel#103]
problem: when i use vertical mode.it seems hava conflict with body element's touch event.
resolve: add document.addEventListener('touchmove', function(e){e.preventDefault()}, false) ta body.
phone: android.  WeChat 6.6.6

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23515964/40095123-ed32b158-58fc-11e8-9fa3-651ef353d3e4.gif)

**Comment by amio** [comment]
What's the user agent on that device? https://motool.github.io/ua/
