### ISSUE TITLE
Use the keyboard to navigate between sliders

### ISSUE THREAD

**Issue by CharlyJazz** [amio/re-carousel#112]
I would like to work on this new feature.

Increase the accessibility of the carousel.

It would be a new prop

**Comment by amio** [comment]
Nice feature, currently it can be achieved using widgets api:
```js
export default class KeyboardNavigator extends React.Component {
  componentDidMount () {
    const { index, total, loop, prevHandler, nextHandler } = props
    // Add event listener, call prevHandler/nextHandler on keypress
  }
  componentWillUnmount () {
    // Cleanup event listeners.
  }
  render () { return null }
}
```

**Comment by CharlyJazz** [comment]
So we should not work on this, as a feature?

**Comment by CharlyJazz** [comment]
I agree, but then we should add that in the documention because the accessibility its a important goal
