### ISSUE TITLE
Animation Overlapping

### ISSUE THREAD

**Issue by ryanfitzer** [amio/re-carousel#113]
Only happens when you use `loop` AND have only 2 frames. Add a 3rd frame and the issue goes away. 

The current frame animates to the right and the incoming frame animates in from the left, overlapping the current frame's animation.

![animation](https://media.giphy.com/media/2AM8ESaKH31vGL3cbD/giphy.gif)

**Comment by amio** [comment]
I think this can be fixed in the rewrite with `react-motion`. We should remove the hidden frames from DOM tree, inject new frame at the beginning of every switch.

**Comment by ryanfitzer** [comment]
Haven’t used `react-motion` before, but sounds like a good plan.

**Comment by hemel-cse** [comment]
Also having this issue.

**Comment by ryanfitzer** [comment]
@amio Do you have an idea when you expect to release this update?

**Comment by amio** [comment]
Hmm, I should fix it on current version first. Don't have too much time experimenting on `react-motion` recently.

**Comment by amio** [comment]
Fixed in [v2.3.0](https://github.com/amio/re-carousel/releases/tag/v2.3.0).
@ryanfitzer @hemel-cse You may have a try now :D

**Comment by ryanfitzer** [comment]
Works like a charm! Thanks for the quick turnaround.

**Comment by hemel-cse** [comment]
Thanks for the fix!
