### ISSUE TITLE
Not swiping in my react app

### ISSUE THREAD

**Issue by AnitaJosic** [amio/re-carousel#118]
Hi.
I have included the carousel to my react App.js that contains further js ./component/ classes inside its div elements.
For example my "Post.js" in 
`<carousel axis={this.state.axis} widgets={ [ Other, Post, ..] } className="custom-class">`
`   <p style={{backgroundColor: 'royalblue', height: '100%'}}>`
`               <Post />`
`   </p>`

The app is loading all the content i have imported and added into the divs in a sequence (no errors), so it's all loaded and visible on one page - but without swiping at all - one js content under the other.

Did I miss a thing? Do I have to enable anything in css (like I have to enable dragable in html5?) or in my browser or do I need to use frames instead of divs or whatever?

Thanks and best regards,
Nini

**Comment by amio** [comment]
Is it only one frame?

**Comment by AnitaJosic** [comment]
I am using the carousel tag like in your example with three of the slides
inside, each containing one importet js except the last one .. the last
slide contains 2 of my importet js classes...


Am Fr., 25. Jän. 2019, 09:43 hat amio <notifications@github.com>
geschrieben:

**Comment by amio** [comment]
Could you provide an example like [codesandbox](https://codesandbox.io) for reproducing this issue?

**Comment by AnitaJosic** [comment]
https://codesandbox.io/s/my0r327rzy

**Comment by amio** [comment]
@AnitaJosic You can start by fiddling this https://codesandbox.io/s/q76q4k8woq

**Comment by AnitaJosic** [comment]
Yeah.... this is exactly what I am using ... i just renamed it in my
example : instead of Carousel i wrote SwipeView.... But OK, seems Like You
don't know either why my example is not working ..

Am Sa., 26. Jän. 2019, 02:42 hat amio <notifications@github.com>
geschrieben:

**Comment by AnitaJosic** [comment]
Found the missing part: enableMouseEvents

**Comment by lluisrojass** [comment]
This can be closed then?

**Comment by amio** [comment]
Yep, thanks for reminder!
