### ISSUE TITLE
Unable to change slide if frame's child intercepts the click/touch events

### ISSUE THREAD

**Issue by rpastorelle** [amio/re-carousel#30]
Awesome component! I love it & want to use it, but can't...

If the frames contain an element that responds to click/touch events, then the events don't propagate up to the parent and this component becomes unusable.

For example, if the frames only contain YouTube embeds...

```
<Carousel>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/J---aiyznGQ" frameBorder="0" allowFullScreen></iframe>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/J---aiyznGQ" frameBorder="0" allowFullScreen></iframe>
</Carousel>
```

Can be avoided if there was next/previous buttons to manually trigger a slide transition.

**Comment by amio** [comment]
Good point, adding event listeners to the capture phase should work too

**Comment by amio** [comment]
In your example code the youtube videos are inside iframe, while event won't propagate from an iframe to parent window. Nothing we can do here
