### ISSUE TITLE
A bug that occurs when sliding to the right after initialization

### ISSUE THREAD

**Issue by caigehui** [amio/re-carousel#51]
# Reproduce

1. Use a mobile device to access the [demo](https://amio.github.io/re-carousel/)

2. Slide "frame1" to the right. "frame1" is above "frame2"，but it should have been "frame3" 

![fullsizerender](https://cloud.githubusercontent.com/assets/9214907/25333670/c4b3b2f0-291d-11e7-9e40-c1d12623d6fa.jpg)

3. Now "frame2" is active. Then slide "frame2" to the right ，"frame2"  becomes "frame3" immediately when "onTouchMove"

4. Everything works fine after step 3

**Comment by amio** [comment]
Confirmed, thanks for reporting!

**Comment by caigehui** [comment]
Any plan to fix this bug ?

**Comment by amio** [comment]
2.0 is ongoing, this will get fixed soon.

**Comment by amio** [comment]
2.0 is out. @caigehui it should be OK by now :-)

**Comment by caigehui** [comment]
It's great!
