### ISSUE TITLE
Auto sliding

### ISSUE THREAD

**Issue by ssageghi** [amio/re-carousel#61]
Hi
thanks for your amazing slider 
auto sliding doesn't start until I slide once

**Comment by amio** [comment]
Could you provide an example that reproduce this problem?

**Comment by NoSoyTsundere** [comment]
I got the same bug.

I'll look into the code to see what is happening.

**Comment by amio** [comment]
Would you try if v2.0.2 also have this problem?

**Comment by NoSoyTsundere** [comment]
@amio work fine on v2.0.2

Ps. this module is awesome. Good work ^-^

**Comment by NoSoyTsundere** [comment]
I think I got it:

On the constructor the `mounted` property is set to `false` and `prepareAutoSlide` is invoked on `componentDidMount()` before `mounted` is `true` so the auto slide will not work
```
constructor (props) {
    {...}
    this.mounted = false
}
componentDidMount () {
    this.prepareAutoSlide()
    for (let i = 1; i < this.state.frames.length; i++) {
      this.refs['f' + i].style.opacity = 0
    }
    this.mounted = true <<<<<<<<<<<<
}
{...}
{...}
prepareAutoSlide () {
    {...}
    if (this.props.loop && this.props.auto && this.mounted) { <<<<<<<<<<<<
      // auto slide only avalible in loop mode
      const slideTimeoutID = setTimeout(this.autoSlide, this.props.interval)
      this.setState({ slider: slideTimeoutID })
    }
  }
```

**Comment by amio** [comment]
Thanks @NoSoyTsundere , it's a regression bug.

I should fix this soon, while before that you may use v2.0.2 instead :)

**Comment by ssageghi** [comment]
it working on v 2.0.2 
i will be waiting for fix 
thanks

**Comment by amio** [comment]
This should have been fixed by now. If it appears again, feel free to reopen this :)
